[profile.default]
src = "foundry/src"
out = "out"
test = "foundry/test"
libs = ["foundry/lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
